spring.application.name=integration_with_bakong_khqr

spring.datasource.url=jdbc:postgresql://localhost:5432/bakong_khqr_02
server.port=9090
spring.datasource.username=postgres
spring.datasource.password=endy123$$&&
spring.datasource.hikari.auto-commit=true