spring.application.name=integration_with_bakong_khqr
server.port=9090

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.auto-commit=${AUTO_COMMIT}

# Bakong API
bakong.api.token=${BAKONG_API_TOKEN}
bakong.api.base-url=${BAKONG_API_BASE_URL}
bakong.api.account-id=${BAKONG_API_ACCOUNT_ID}
bakong.api.merchant-name=${BAKONG_API_MERCHANT_ID}
bakong.api.merchant-city=${BAKONG_API_MERCHANT_ID}